sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
    - libxml2-dev
    - libfltk1.3-dev
    - fluid
    - libcpptest-dev
    - libjpeg-dev
    - libglm-dev
    - libcminpack-dev
    - libglew-dev
    - python-dev
script:
 - export PYTHON_LIBRARY=$(python-config --ldflags|cut -d' ' -f1|cut -c3-)/lib$(python-config --ldflags|cut -d' ' -f3|cut -c3-).so
 - export PYTHON_INCLUDE_DIR=$(python-config --cflags|cut -d' ' -f1|cut -c3-)
 - export PYTHON_INCLUDE_PATH=$(python-config --cflags|cut -d' ' -f1|cut -c3-)
 
 - mkdir build; cd build
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=$PYTHON_LIBRARY -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR -DPYTHON_INCLUDE_PATH=$PYTHON_INCLUDE_PATH -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject;
   fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=$PYTHON_LIBRARY -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR -DPYTHON_INCLUDE_PATH=$PYTHON_INCLUDE_PATH -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_CPPTEST=true -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject; 
   fi
 - make
 - ~/OpenVSP_Install/vspscript -script ../examples/scripts/TestAll.vspscript
 - ~/OpenVSP_Install/apitest
